### ISSUE TITLE
program doesn't run

### ISSUE THREAD

**Issue by YulTheNinja** [ahihiyou20/discord-selfbot-owo-bot#24]
I've tried many things such as redownloading python, cloning the repository again, restarting my computer, etc. but it's still not working. 

30 Dec 2023 20:29:12 - WARNING - Loading... Please be patient!
Traceback (most recent call last):
  File "C:\Users\yulth\discord-selfbot-owo-bot\main.py", line 691, in <module>
    client.run(client.token)
  File "C:\Users\yulth\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 631, in run
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\yulth\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 610, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\yulth\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 573, in start
    await self.login(*args)
  File "C:\Users\yulth\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 424, in login
    await self.http.static_login(token.strip())
                                 ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by YulTheNinja** [comment]
I couldn't upload a screenshot, so I copied it instead

**Comment by YulTheNinja** [comment]
Okay, I was supposed to put things in config.json

**Comment by YulTheNinja** [comment]
AttributeError: 'str' object has no attribute 'send'

**Comment by firinggamers** [comment]
> AttributeError: 'str' object has no attribute 'send'

did you fix it?
